FROM debian:bookworm-slim

ENV PIP_BREAK_SYSTEM_PACKAGES 1

RUN apt-get update -qq && \
    apt-get -yqq install python3 python3-pip python3-dev libssl-dev && \
    useradd mine
WORKDIR /home/mine/

COPY tictotactotoe tictotactotoe
COPY entrypoint.sh requirements.txt /home/mine/

RUN pip3 install -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f requirements.txt

ENTRYPOINT ["/bin/bash", "/home/mine/entrypoint.sh"]
