FROM debian:bookworm-slim
ENV PIP_BREAK_SYSTEM_PACKAGES 1
RUN apt-get update && apt-get --assume-yes install python3 python3-pip python3-dev libssl-dev
RUN useradd mine
WORKDIR /home/mine/
COPY requirements.txt /home/mine/requirements.txt
RUN pip3 install -r requirements.txt
# This is for the GUI
RUN mkdir -p /home/mine/tictotactotoe-ui/
WORKDIR /home/mine/tictotactotoe-ui/
COPY tictotactotoe-ui/package.json /home/mine/tictotactotoe-ui/package.json
COPY tictotactotoe-ui/package-lock.json /home/mine/tictotactotoe-ui/package-lock.json
RUN apt-get update &&  \
    apt-get --assume-yes install curl nginx && \
    curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -yqq nodejs && \
    npm install
WORKDIR /home/mine/
COPY nginx/nginx.dev.template /etc/nginx/nginx.conf
ENTRYPOINT ["/bin/bash", "/home/mine/entrypoint.dev.sh"]
